export default {
	VITE_OPENSEA_API_PREFIX: import.meta.env.VITE_OPENSEA_API_PREFIX,
	VITE_OPENSEA_PROXY_REGISTRY: import.meta.env.VITE_OPENSEA_PROXY_REGISTRY,
	VITE_MAINNET: import.meta.env.VITE_MAINNET,
};
